version: "2"

services:
    mongodb:
        image: mongo:3.2
        ports:
            - "27017:27017"
        volumes:
            - ./mongodb-data/:/data/db
        # hostname: mongodb
        # domainname: coclab.lan
        cpu_shares: 512             # 0.5 CPU
        mem_limit: 536870912        # 512 MB RAM
        # privileged: true
        # restart: always
        # stdin_open: true
        # tty: true

